'use strict';
(() => {
 const panel=document.getElementById('forge-approval-panel');if(!panel)return;
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const labels={revise:'Revise',decline:'Decline',snooze:'Snooze',approve:'Approve',auto_approve:'Auto-approve implementation'};
 let snapshot=null,selected=null,busy=false,filter={gate:'',client:'',project:'',status:'',waiting:'',feedback:'',delivery:'',grant:''};
 const dialog=document.createElement('dialog');dialog.id='forge-approval-dialog';dialog.setAttribute('aria-label','Approval review');document.body.append(dialog);
 async function api(body) {
  if(window.ForgeHost) {
   const view={'forge.snapshot':'approvalSnapshot','forge.catalog':'proposals','forge.proposal':'proposal'}[body.mode];
   if(!view)throw Error('Web approval actions are awaiting activation');
   return window.ForgeHost.read(view,body.input||{});
  }
  const response=await fetch('/api/forge/approvals',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-Forge-Request':'approval.v1'},body:JSON.stringify(body)});
  const result=await response.json();if(!response.ok||result.ok===false)throw Error(result.error||'Approval service unavailable');return result.result;
 }
 const catalog=document.createElement('section');catalog.id='forge-native-proposals';panel.after(catalog);
 let nativeRows=[],nativeTotal=0,nativeOffset=0,nativeSearch='',nativeState='',nativeSelected=null;
 const command=(name,input)=>api({mode:'forge.command',command:name,input});
 const stamp=value=>value?new Date(value).toLocaleString():'Not scheduled';
 const active=w=>w.documents.find(d=>d.gate===w.gate&&d.version===(w.gate==='scope'?w.scope_version:w.plan_version));
 function ribbon(w) {return `<ol class="approval-ribbon" aria-label="Approval stages">${['proposal','scope','plan'].map((g,i)=>`<li class="${g===w.gate?'current':''}"><span aria-hidden="true">${['◇','▤','▶'][i]}</span> ${g}</li>`).join('')}</ol>`;}
 function options(key,label) {
  const values=[...new Set(snapshot.workflows.map(w=>w[key]).filter(Boolean))];
  return `<label>${label}<select data-filter="${key}"><option value="">All</option>${values.map(v=>`<option ${filter[({client_id:'client',project_id:'project',state:'status',waiting:'waiting',feedback:'feedback',delivery:'delivery',grant:'grant'})[key]||key]===v?'selected':''} value="${esc(v)}">${esc(v)}</option>`).join('')}</select></label>`;
 }
 function render() {
  if(!snapshot)return;
  const filterOpen=panel.querySelector('.approval-filter-drawer')?.open||false;
  const rows=snapshot.workflows.filter(w=>(!filter.gate||filter.gate===w.gate)&&(!filter.client||filter.client===w.client_id)&&(!filter.project||filter.project===w.project_id)&&(!filter.status||filter.status===w.state)&&(!filter.waiting||filter.waiting===(w.state==='review'?'greg':w.state==='validation_pending'?'validator':w.gate==='scope'&&w.state==='approved'?'planner':'none'))&&(!filter.feedback||filter.feedback===(w.events.some(e=>e.role==='client')?'received':'waiting'))&&(!filter.delivery||w.deliveries.some(d=>d.state===filter.delivery))&&(!filter.grant||filter.grant===(w.grant_data&&!w.grant_revoked?'active':'manual')));
  panel.innerHTML=`<div class="approval-heading">${snapshot.mode==='local_pilot'?'<a class="panel-button" href="/mailbox" target="_blank" rel="noopener">Email previews &#8599;</a>':''}<span class="chip">${snapshot.mode==='local_pilot'?'Local pilot · synthetic proposals':snapshot.mode==='live_read_only'?'Supabase - Read only':snapshot.mode==='internal_live'?'Supabase - Internal email pilot':'Approval workflow'}</span><button class="panel-button" data-refresh>↻ <span class="sr-only">Refresh approvals</span></button></div><details class="approval-filter-drawer" ${filterOpen?'open':''}><summary>Filters</summary><div class="approval-filters">${options('gate','Gate')}${options('client_id','Client')}${options('project_id','Project')}${options('state','Status')}${[['waiting','Waiting on',[['greg','Greg'],['validator','Validator'],['planner','Planner']]],['feedback','Feedback',[['received','Received'],['waiting','Waiting']]],['delivery','Delivery',[['ambiguous','Needs reconciliation'],['failed','Failed'],['delivered','Delivered']]],['grant','Implementation',[['active','Opt-in active'],['manual','Manual approval']]]].map(([k,label,values])=>`<label>${label}<select data-filter="${k}"><option value="">All</option>${values.map(([v,l])=>`<option value="${v}" ${filter[k]===v?'selected':''}>${l}</option>`).join('')}</select></label>`).join('')}</div></details><div class="approval-cards">${rows.map(w=>`<article class="approval-card">${ribbon(w)}<h4>${esc(w.title)}</h4><div class="approval-chips"><span title="Client" aria-label="Client ${esc(w.client_id||'Unassigned')}">♧ ${esc(w.client_id||'Unassigned')}</span><span title="Project">▣ ${esc(w.project_id||'No project')}</span><span title="Current document version">▤ v${Math.max(w.scope_version,w.plan_version,1)}</span><span title="Client feedback">☏ ${w.events.filter(e=>e.role==='client').length}</span>${w.grant_data&&!w.grant_revoked?'<span title="Bounded implementation opt-in">⚡ Opt-in</span>':''}</div><div class="approval-next"><strong>${esc(w.state.replaceAll('_',' '))}</strong><button class="panel-button primary" data-approval-open="${esc(w.workflow_id)}">${w.state==='proposed'?'Review proposal':w.state==='draft'||w.state==='changes_requested'?(w.gate==='scope'?'Edit scope':'Revise plan'):'Open review'}</button></div></article>`).join('')||'<p>No proposals match these filters.</p>'}</div><p class="tiny" role="status">${snapshot.workflows.length} linked workflows · ${snapshot.connection?'Implementation stays manual':'decisions read from the service'}</p>`;
  if(snapshot.connection&&!snapshot.workflows.length)panel.innerHTML=`<div class="approval-heading"><span class="chip">${snapshot.mode==='live_read_only'?'Supabase - Read only':'Supabase - Internal email pilot'}</span><button class="panel-button" data-refresh aria-label="Refresh approvals">&#8635;</button></div>`;
  const legacy=document.getElementById('forge-proposal-examples');if(legacy)legacy.hidden=true;
 }
 function field(name,title,value='',type='text') {return `<label>${title}<input name="${name}" type="${type}" value="${esc(value)}"></label>`;}
 function detail(id) {
  selected=id;const w=snapshot.workflows.find(w=>w.workflow_id===id);if(!w)return;const d=active(w),s=w.documents.find(d=>d.gate==='scope'&&d.version===w.scope_version);
  let main='';
  if(w.gate==='proposal')main='<p>Accepting creates an editable scope intake. Email starts after the scope is ready for review.</p><button class="panel-button primary" data-accept>Accept proposal</button>';
  else if(w.gate==='scope'&&['draft','changes_requested'].includes(w.state)) {
   const body=s?.body||{};main=`<form id="approval-scope-form" class="approval-form">${field('outcome','Outcome',body.outcome||w.title)}${field('deliverables','Deliverables (one per comma)',(body.deliverables||['report']).map(d=>d.id||d).join(', '))}${field('acceptance','Acceptance criteria (one per comma)',(body.acceptance||['report-verified']).map(d=>d.id||d).join(', '))}${field('exclusions','Excluded work',(body.exclusions||['production']).join(', '))}${field('repositories','Repository',(body.repositories||['gbautomation']).join(', '))}${field('environment','Environment',body.environment||'local')}<label>Reviewer<select name="reviewer"><option value="greg">Greg ? decision authority</option></select></label><label>Client feedback recipient<select name="client_recipient">${(snapshot.recipient_options||[]).filter(r=>r.client_id==='*'||r.client_id===w.client_id).map(r=>`<option value="${esc(r.id)}" ${body.client_recipient===r.id?'selected':''}>${esc(r.label)}</option>`).join('')}</select></label>${field('dependencies','Dependencies (optional)',(body.dependencies||[]).join(', '))}<button class="panel-button primary">Ready for scope review</button></form>`;
  } else {
   main=`<div class="approval-document"><h3>${esc(d?.body.outcome||s?.body.outcome||w.title)}</h3><p>${w.gate==='scope'?'Scope approval permits planning.':'Plan approval permits only the bound implementation.'}</p><ul>${(d?.body.deliverables||d?.body.deliverable_ids||[]).map(x=>`<li>${esc(x.title||x.id||x)}</li>`).join('')}</ul>${d?.body.binding?`<div class="approval-chips"><span title="Permitted phases">Phases ${esc(d.body.binding.phases.join(', '))}</span><span title="Validation state">${w.state==='validation_pending'?'Validation pending':'Validation recorded'}</span><span title="Execution target">${esc(d.body.binding.targets.join(', '))}</span></div>`:''}<p class="tiny">${esc(d?.sha256?.slice(0,16)||'Awaiting document')} · ${esc(w.state.replaceAll('_',' '))}</p></div>`;
   if(w.state==='review') main+=`<form id="approval-decision-form" class="approval-form"><label>Decision<select name="action">${Object.entries(labels).filter(([k])=>k!=='auto_approve'||(w.gate==='scope'&&snapshot.engineering)).map(([k,v])=>`<option value="${k}" ${k==='approve'?'selected':''}>${v}</option>`).join('')}</select></label><label>Note<textarea name="note" maxlength="2000"></textarea></label><div id="approval-snooze" hidden>${field('snooze_until','Resume reminders',new Date(Date.now()+86400000).toISOString().slice(0,16),'datetime-local')}</div><div id="approval-grant" hidden><p>Only this scope, repository and local environment. The generated plan still needs independent validation.</p>${field('max_cost','Maximum implementation cost',0,'number')}${field('expires_at','Grant expires',new Date(Date.now()+86400000).toISOString().slice(0,16),'datetime-local')}</div><button class="panel-button primary">Confirm decision</button></form>`;
   if(w.gate==='scope'&&w.state==='approved'&&snapshot.mode==='local_pilot')main+='<button class="panel-button primary" data-build-fixture>Create pilot plan</button>';
   if(w.grant_data&&!w.grant_revoked)main+='<button class="panel-button" data-revoke>Revoke implementation opt-in</button>';
   if(!['declined','draft','changes_requested'].includes(w.state))main+='<button class="panel-button" data-revise>Request a scope revision</button>';
  }
  dialog.innerHTML=`<form method="dialog"><button class="dialog-close" aria-label="Close approval review">×</button></form><span class="eyebrow">${snapshot.mode==='local_pilot'?'LOCAL PILOT':'GREG APPROVES · CLIENTS GIVE FEEDBACK'}</span><h2>${esc(w.title)}</h2><p class="tiny">${esc(w.client_id||'Unassigned client')} &#183; ${esc(w.project_id||'Unassigned project')}</p>${ribbon(w)}<div id="approval-detail">${main}</div><p id="approval-error" role="alert"></p><details><summary>Linked records and history</summary><dl class="approval-links"><dt>Proposal</dt><dd>${esc(w.proposal_id)}</dd><dt>Client</dt><dd>${esc(w.client_id||'Unassigned')}</dd><dt>Project</dt><dd>${esc(w.project_id||'Unassigned')}</dd><dt>Scope</dt><dd>v${w.scope_version}</dd><dt>Plan</dt><dd>v${w.plan_version}</dd></dl><div class="approval-artifacts">${(w.artifacts||[]).filter(a=>a.document_version===w.plan_version).map(a=>`<a class="panel-button" href="/artifact?path=${encodeURIComponent(a.source_ref)}" target="_blank" rel="noopener">${esc(a.kind)} v${a.document_version} ?</a>`).join('')}</div><ol class="approval-timeline">${w.events.map(e=>`<li><strong>${esc(e.action.replaceAll('_',' '))}</strong> · ${esc(e.role)}<small>${stamp(e.created_at)}</small></li>`).join('')}</ol></details><details><summary>Deliveries and reminders</summary>${w.deliveries.map(o=>`<p>${esc(o.kind.replaceAll('_',' '))} · ${esc(o.recipient_role||'workflow')} · <strong>${esc(o.state)}</strong>${o.result?.channel==='fixture'?' · local email fixture':''}</p>`).join('')}${w.reminders.map(r=>`<p>◷ ${esc(r.recipient_role)} · ${stamp(r.wake_at)}</p>`).join('')}</details>`;
  if(!dialog.open)dialog.showModal();history.replaceState(null,'','#approval='+encodeURIComponent(id));
 }
 async function refresh(reopen=false) {
  try {snapshot=await api({mode:'forge.snapshot'});render();if(snapshot.connection)await loadCatalog();if(reopen&&selected)detail(selected);}
  catch {panel.innerHTML='<p class="tiny" role="status">Approval service is not connected. <button class="panel-button" data-refresh>Retry</button></p>';}
 }
 async function loadCatalog() {
  const page=await api({mode:'forge.catalog',input:{offset:nativeOffset,search:nativeSearch,state:nativeState}});
  nativeRows=page.rows;nativeTotal=page.total;
  catalog.innerHTML=`<div class="approval-heading"><h3>GBAuto proposals</h3><span class="chip" title="Tenant pinned by the private server">${esc(snapshot.connection.tenant)}</span></div><form class="approval-catalog-filter"><label class="sr-only" for="native-search">Search proposals</label><input id="native-search" name="search" value="${esc(nativeSearch)}" placeholder="Find a proposal"><label class="sr-only" for="native-state">Proposal status</label><select id="native-state" name="state">${[['','All statuses'],['gated','Awaiting review'],['approved','Previously approved']].map(([v,l])=>`<option value="${v}" ${nativeState===v?'selected':''}>${l}</option>`).join('')}</select><button class="panel-button">Search</button></form><p class="tiny">${snapshot.connection.writes_enabled?'Scope emails go only to '+esc(snapshot.connection.recipient)+'. Review links open on this PC.':'Live records are connected. Approval writes and email await activation.'}</p><div class="approval-cards">${page.rows.map(p=>`<article class="approval-card"><h4>${esc(p.card_title)}</h4><div class="approval-chips"><span title="Source">&#8599; ${esc(({youtube_transcript:'YouTube',transcript:'Transcript'})[p.source_type]||p.source_type.replaceAll('_',' '))}</span><span title="Proposal type">&#9671; ${esc(p.card_type==='expert-portfolio-proposal'?'Expert proposal':p.card_type.replaceAll('-',' '))}</span><span title="Native proposal status">${esc(p.state)}</span>${p.source_synthetic?'<span title="Source marked this record synthetic">Test record</span>':''}${p.task_id?`<span title="Linked task ${esc(p.task_id)}">&#9635; Task</span>`:''}</div><button class="panel-button" data-native-open="${esc(p.proposal_id)}">Review proposal</button></article>`).join('')||'<p>No matching proposals.</p>'}</div><div class="approval-heading"><button class="panel-button" data-native-page="-1" ${nativeOffset===0?'disabled':''}>&#8592; Previous</button><span class="tiny">${page.total?nativeOffset+1:0}-${nativeOffset+page.rows.length} of ${page.total}</span><button class="panel-button" data-native-page="1" ${nativeOffset+page.rows.length>=page.total?'disabled':''}>Next &#8594;</button></div>`;
 }
 async function nativeDetail(id) {
  const existing=snapshot.workflows.find(w=>w.proposal_id===id);if(existing){detail(existing.workflow_id);return;}
  nativeSelected=nativeRows.find(p=>p.proposal_id===id);if(!nativeSelected)return;
  if(window.ForgeHost) {
   const row=await api({mode:'forge.proposal',input:{proposal_id:id}});
   if(!row)throw Error('Proposal no longer available');
   nativeSelected=row;
  }
  const p=nativeSelected;
  dialog.innerHTML=`<form method="dialog"><button class="dialog-close" aria-label="Close approval review">&#215;</button></form><span class="eyebrow">LIVE PROPOSAL ? ${esc(p.state)}</span><h2>${esc(p.card_title)}</h2><div class="approval-chips"><span>? ${esc(({youtube_transcript:'YouTube',transcript:'Transcript'})[p.source_type]||p.source_type.replaceAll('_',' '))}</span><span>? ${esc(p.card_type==='expert-portfolio-proposal'?'Expert proposal':p.card_type.replaceAll('-',' '))}</span></div><p>Accept this proposal to complete its scope. Submitting the scope sends the internal review email.</p><button class="panel-button primary" data-native-accept ${!snapshot.connection.writes_enabled||p.state!=='gated'?'disabled':''}>Accept proposal</button>${!snapshot.connection.writes_enabled?'<p class="tiny">Approval service awaiting activation.</p>':''}${p.state!=='gated'?'<p class="tiny">This proposal already has a native decision. It is available for reference.</p>':''}<p id="approval-error" role="alert"></p><details><summary>Linked records</summary><dl class="approval-links"><dt>Proposal</dt><dd>${esc(p.proposal_id)}</dd><dt>Source</dt><dd>${esc(p.source_type)}</dd><dt>Task</dt><dd>${esc(p.task_id||'Not assigned')}</dd><dt>Route</dt><dd>${esc(p.workflow_route)}</dd></dl></details>`;
  if(!dialog.open)dialog.showModal();
  const brief=document.createElement('section');brief.className='approval-document';
  brief.innerHTML=`${p.summary?`<p>${esc(p.summary)}</p>`:'<p class="tiny">No additional summary was saved with this proposal.</p>'}${p.action_items?.length?`<ul>${p.action_items.map(item=>`<li>${esc(item)}</li>`).join('')}</ul>`:''}<p class="tiny">Updated ${esc(stamp(p.updated_at))}</p>`;
  dialog.querySelector('h2').after(brief);
 }
 catalog.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.target);nativeSearch=String(f.get('search')||'');nativeState=String(f.get('state')||'');nativeOffset=0;try{await loadCatalog();}catch{catalog.innerHTML='<p role="alert">Live proposal read unavailable. Refresh to retry.</p>';}});
 catalog.addEventListener('click',async e=>{const b=e.target.closest('button');if(b?.dataset.nativeOpen){b.disabled=true;try{await nativeDetail(b.dataset.nativeOpen);}catch{catalog.insertAdjacentHTML('afterbegin','<p role="alert">Proposal unavailable. Please retry.</p>');}finally{b.disabled=false;}}if(b?.dataset.nativePage){nativeOffset=Math.max(0,nativeOffset+Number(b.dataset.nativePage)*50);try{await loadCatalog();}catch{catalog.innerHTML='<p role="alert">Live proposal read unavailable. Refresh to retry.</p>';}}});
 async function mutate(fn) {
  if(busy)return;busy=true;dialog.querySelectorAll('button').forEach(b=>b.disabled=true);
  try {await fn();await refresh(true);}catch(e){document.getElementById('approval-error').textContent=e.message.replaceAll('_',' ');}finally{busy=false;dialog.querySelectorAll('button').forEach(b=>b.disabled=false);}
 }
 panel.addEventListener('click',e=>{const b=e.target.closest('button');if(b?.hasAttribute('data-refresh'))refresh();if(b?.dataset.approvalOpen)detail(b.dataset.approvalOpen);});
 panel.addEventListener('change',e=>{const map={gate:'gate',client_id:'client',project_id:'project',state:'status',waiting:'waiting',feedback:'feedback',delivery:'delivery',grant:'grant'};if(map[e.target.dataset.filter]){filter[map[e.target.dataset.filter]]=e.target.value;render();}});
 dialog.addEventListener('change',e=>{if(e.target.name==='action'){document.getElementById('approval-snooze').hidden=e.target.value!=='snooze';document.getElementById('approval-grant').hidden=e.target.value!=='auto_approve';}});
 dialog.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
  if(b.classList.contains('dialog-close')){e.preventDefault();dialog.close();return;}
  if(b.hasAttribute('data-native-accept'))mutate(async()=>{const registered=await command('register',{proposal_id:nativeSelected.proposal_id});selected=registered.workflow_id;await command('accept',{workflow_id:selected});});
  if(b.dataset.retry)mutate(()=>api({mode:'forge.retry',workflow_id:selected,outbox_id:b.dataset.retry}));
  if(b.hasAttribute('data-accept'))mutate(()=>command('accept',{workflow_id:selected}));
  if(b.hasAttribute('data-revoke'))mutate(()=>command('revoke_grant',{workflow_id:selected}));
  if(b.hasAttribute('data-revise'))mutate(()=>command('revise',{workflow_id:selected,gate:'scope'}));
  if(b.hasAttribute('data-build-fixture'))mutate(()=>api({mode:'pilot.plan',workflow_id:selected}));
 });
 dialog.addEventListener('submit',e=>{
  if(e.target.id==='approval-scope-form') {e.preventDefault();const f=new FormData(e.target),split=k=>String(f.get(k)||'').split(',').map(s=>s.trim()).filter(Boolean);mutate(()=>command('scope',{workflow_id:selected,document:{outcome:f.get('outcome'),deliverables:split('deliverables'),acceptance:split('acceptance'),exclusions:split('exclusions'),repositories:split('repositories'),environment:f.get('environment'),reviewer:f.get('reviewer'),client_recipient:f.get('client_recipient'),dependencies:split('dependencies')}}));}
  if(e.target.id==='approval-decision-form') {e.preventDefault();const f=new FormData(e.target),action=f.get('action'),w=snapshot.workflows.find(w=>w.workflow_id===selected),d=active(w);const input={mode:'forge.decide',action,note:f.get('note'),confirmed:true};
   if(action==='snooze')input.snooze_until=new Date(f.get('snooze_until')).toISOString();
   if(action==='auto_approve')input.grant={...snapshot.engineering,repositories:d.body.repositories,environments:[d.body.environment],operations:['code','test','docs'],phases:[0,1,2,3,4,5],max_cost:Number(f.get('max_cost')),expires_at:new Date(f.get('expires_at')).toISOString(),excluded_actions:d.body.exclusions};
   mutate(async()=>{const minted=await api({mode:'forge.mint',workflow_id:selected,recipient_role:'operator'});await api({...input,capability:minted.capability});});
  }
 });
 if(window.ForgeHost||location.protocol!=='file:')refresh().then(()=>{const id=new URLSearchParams(location.hash.slice(1)).get('approval');if(snapshot?.workflows.some(w=>w.workflow_id===id))detail(id);});
 else panel.innerHTML='<p class="tiny">Connect the private approval service to accept proposals and review scopes.</p>';
})();
