"""Generate the service-only hosted read RPC from Forge's existing projections."""
from pathlib import Path

from forge_history import query_sql
from forge_planning import prd_sql

ROOT = Path(__file__).resolve().parents[4]
OUTPUT = ROOT / 'supabase/migrations/20260922200000_forge_atlas_hosted_read.sql'
SCOPE = {'tenant_id': 'rpc-tenant', 'agent_id': 'rpc-expert'}


def parameters(sql):
    for value, parameter in [('rpc-tenant', 'p_tenant'), ('rpc-expert', 'p_expert'),
                             ('rpc-session', 'p_session_key'), ('rpc-message', 'p_message_key'),
                             ('rpc-cursor', 'p_after')]:
        sql = sql.replace("'" + value + "'", parameter)
    return sql


def aggregate(sql):
    return "select coalesce(jsonb_agg(to_jsonb(q)), '[]'::jsonb) into result from (" + parameters(sql) + ') q;'


def build():
    branches = []
    for view in ('sessions', 'messages', 'traces'):
        for message in ((False, True) if view == 'traces' else (False,)):
            for cursor in (False, True):
                sql = query_sql(SCOPE, view, 'rpc-session' if view != 'sessions' else None,
                                'rpc-message' if message else None, 'rpc-cursor' if cursor else None)
                condition = f"p_view='{view}' and p_after is {'not ' if cursor else ''}null"
                if view == 'traces':
                    condition += f" and p_message_key is {'not ' if message else ''}null"
                branches.append(f"  {'if' if not branches else 'elsif'} {condition} then\n    {aggregate(sql)}")
    prds = parameters(prd_sql(SCOPE))
    # Every supplied tenant/expert claim must agree, matching exact_owner().
    prds = f"""select p.* from ({prds}) p where not exists (
      select 1 from (values
        (p.client,p_tenant),(p.tenant_id,p_tenant),
        (p.frontmatter->>'client',p_tenant),(p.frontmatter->>'tenant_id',p_tenant),
        (p.metadata#>>'{{master_sheet_projection,tenant_id}}',p_tenant),
        (p.source_refs#>>'{{forge,tenant_id}}',p_tenant),
        (p.owner_expert,p_expert),(p.frontmatter->>'owner_expert',p_expert),
        (p.metadata#>>'{{master_sheet_projection,owner_expert}}',p_expert),
        (p.source_refs#>>'{{forge,agent_id}}',p_expert)
      ) claims(value,expected) where value is not null and value<>'' and value<>expected)
      and (p.frontmatter#>'{{source_refs,forge}}' is null
           or p.frontmatter#>'{{source_refs,forge}}'=p.source_refs->'forge')"""
    return """-- Generated by build_hosted_reader_sql.py. No browser role may execute this RPC.
-- Cognito issuer + tenant group are checked by the website Lambda; it pins the expert.
create or replace function public.agent_forge_atlas_read(
  p_tenant text, p_expert text, p_view text,
  p_session_key text default null, p_message_key text default null, p_after text default null
) returns jsonb language plpgsql stable security definer
set search_path = pg_catalog, public set statement_timeout = '12s' as $body$
declare result jsonb;
begin
  if p_tenant is null or p_expert is null or p_view is null
    or p_tenant !~ '^[a-z0-9][a-z0-9_-]{0,119}$' or p_expert !~ '^[a-z0-9][a-z0-9_-]{0,119}$'
    or p_view not in ('sessions','messages','traces','atlas','planning')
    or exists(select 1 from unnest(array[p_session_key,p_message_key,p_after]) value
       where value is not null and (length(value) not between 1 and 512 or value ~ '[[:cntrl:]]'))
    or (p_view in ('messages','traces') and p_session_key is null)
    or (p_view in ('sessions','atlas','planning') and (p_session_key is not null or p_message_key is not null))
    or (p_view<>'traces' and p_message_key is not null)
    or (p_view in ('atlas','planning') and p_after is not null)
  then raise exception 'invalid_forge_read' using errcode='22023'; end if;
""" + '\n'.join(branches) + """
  elsif p_view='atlas' then
    with traces as (
      select trace_id as row_key,trace_timestamp as observed_at,total_tokens as tokens,total_cost as cost,
        latency_sec as duration,null::int as events from public.langfuse_traces
      where tenant=p_tenant and raw_summary#>>'{metadata,expert_id}'=p_expert
        and coalesce(raw_summary#>>'{attribution_evidence,expert_id}','explicit')='explicit'
        and coalesce(raw_summary#>>'{attribution_evidence,tenant}','explicit')='explicit'
        and trace_timestamp>=now()-interval '90 days' order by trace_timestamp desc,trace_id limit 200
    ), runs as (
      select run_id as row_key,started_at as observed_at,null::bigint as tokens,null::numeric as cost,
        extract(epoch from (ended_at-started_at)) as duration,null::int as events from public.agent_runs
      where client_slug=p_tenant and payload->>'expert_id'=p_expert
        and started_at>=now()-interval '90 days' order by started_at desc,run_id limit 200
    ), sessions as (
      select session_key as row_key,started_at as observed_at,null::bigint as tokens,null::numeric as cost,
        extract(epoch from (ended_at-started_at)) as duration,tool_call_count as events from public.agent_sessions
      where client_slug=p_tenant and payload->>'expert_id'=p_expert
        and started_at>=now()-interval '90 days' order by started_at desc,session_key limit 200
    ) select jsonb_build_object(
      'traces',coalesce((select jsonb_agg(to_jsonb(t)) from traces t),'[]'::jsonb),
      'runs',coalesce((select jsonb_agg(to_jsonb(r)) from runs r),'[]'::jsonb),
      'sessions',coalesce((select jsonb_agg(to_jsonb(s)) from sessions s),'[]'::jsonb)) into result;
  elsif p_view='planning' then
    with owned_prds as (""" + prds + """), cards as (
      select t.task_id,t.title,t.status,t.updated_at,array_agg(distinct l.prd_id order by l.prd_id) as prd_ids
      from public.kanban_tasks t join public.prd_kanban_dispatch_links l on l.task_id=t.task_id
      join owned_prds p on p.prd_id=l.prd_id
      where t.client_slug=p_tenant and t.board_slug='gbautomation'
      group by t.task_id,t.title,t.status,t.updated_at order by t.updated_at desc nulls last,t.task_id limit 200
    ) select jsonb_build_object(
      'prds',coalesce((select jsonb_agg(to_jsonb(p)) from owned_prds p),'[]'::jsonb),
      'cards',coalesce((select jsonb_agg(to_jsonb(c)) from cards c),'[]'::jsonb)) into result;
  end if;
  return result;
end $body$;
revoke all on function public.agent_forge_atlas_read(text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.agent_forge_atlas_read(text,text,text,text,text,text) to service_role;
comment on function public.agent_forge_atlas_read(text,text,text,text,text,text) is
  'Bounded Forge Atlas projections. Service-only; website backend owns Cognito tenant/expert authorization.';
"""


if __name__ == '__main__':
    import sys
    sys.path.insert(0, str(ROOT))
    from resources.lib.tracing import trace_agent

    @trace_agent('forge.hosted_reader_sql', metadata={'mode': 'local_generation'})
    def main():
        OUTPUT.write_text(build(), encoding='utf-8')
        print(OUTPUT.name)
    main()
