window.Forge=(()=>{
'use strict';
const $=id=>document.getElementById(id),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths={terminal:'m4 6 6 6-6 6m9 0h7',check:'m5 12 4 4L19 6',error:'M12 8v5m0 3h.01M10 3 2 18a2 2 0 0 0 2 3h16a2 2 0 0 0 2-3L14 3a2 2 0 0 0-4 0',clock:'M12 8v5l3 2M22 12a10 10 0 1 1-20 0 10 10 0 0 1 20 0',play:'m8 4 12 8-12 8Z',stop:'M6 6h12v12H6Z',expand:'M8 3H3v5m13-5h5v5M3 16v5h5m13-5v5h-5',collapse:'M3 8h5V3m13 5h-5V3M8 21v-5H3m13 5v-5h5',shield:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Zm-4 9 3 3 5-6',spark:'m12 2 3 7 7 3-7 3-3 7-3-7-7-3 7-3Z',graph:'M7 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0M21 5a2 2 0 1 1-4 0 2 2 0 0 1 4 0M14 19a2 2 0 1 1-4 0 2 2 0 0 1 4 0M5 7v4l6 6M19 7v4l-6 6M7 5h10',file:'M14 2H5v20h14V7Zm0 0v5h5M8 12h8M8 16h6',folder:'M3 5h6l2 3h10v12H3Z',box:'m12 2 10 5-10 5L2 7Zm-10 5v10l10 5 10-5V7M12 12v10',search:'M20 20l-5-5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0',chevron:'m9 5 7 7-7 7',history:'M3 3v6h6M3 9a9 9 0 1 1 0 7M12 7v6l4 2',download:'M12 3v12m-5-5 5 5 5-5M4 16v5h16v-5',source:'m8 6-6 6 6 6m8-12 6 6-6 6m-3-15-2 18',input:'M4 5h16v14H4ZM8 9v6m3-3h5',arrow:'M3 12h18m-6-6 6 6-6 6',moon:'M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11',sun:'M12 2v2m0 16v2M2 12h2m16 0h2M5 5l1 1m12 12 1 1M5 19l1-1M18 6l1-1M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0',dots:'M12 3a9 9 0 0 1 9 9M12 21a9 9 0 0 1-9-9',minus:'M5 12h14',copy:'M8 8h13v13H8ZM16 8V3H3v13h5',server:'M3 3h18v7H3Zm0 11h18v7H3ZM7 6.5h.01M7 17.5h.01',lock:'M7 10V7a5 5 0 0 1 10 0v3M5 10h14v11H5Z',layout:'M3 3h18v18H3ZM3 9h18M10 9v12',eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm13 0a3 3 0 1 1-6 0 3 3 0 0 1 6 0',layers:'m12 2 10 6-10 6L2 8Zm-10 11 10 6 10-6M2 18l10 6 10-6',refresh:'M20 3v6h-6M4 21v-6h6M4 9a8 8 0 0 1 13-5l3 5M4 15l3 5a8 8 0 0 0 13-5',video:'M3 5h13v14H3Zm13 5 5-3v10l-5-3',message:'M3 3h18v14H9l-6 4Z',brain:'M12 4c-5-5-10 2-7 5-5 3-2 10 3 9 0 4 4 3 4 0Zm0 0c5-5 10 2 7 5 5 3 2 10-3 9 0 4-4 3-4 0M5 9l3 1m8 0 3-1M8 18l1-3m6 0 1 3',settings:'M4 6h16M4 12h16M4 18h16M8 3v6m8 0v6m-5 0v6',tasks:'M8 5h13M8 12h13M8 19h13M3 5h.01M3 12h.01M3 19h.01',link:'m9 15 6-6M8 16l-2 2a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0m2 1 2-2a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0',send:'m2 3 20 9-20 9 4-9Zm4 9h16',user:'M16 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0M4 21v-3a8 8 0 0 1 16 0v3',back:'m9 5-7 7 7 7M2 12h19'};
const icon=n=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true"><path d="${paths[n]||paths.file}"/></svg>`;
const defs=[['skills','Skills Library','spark','skills','Capabilities with their inputs and outputs.'],['commands','Justfile Commands','terminal','commands','Run a recipe and follow its result.'],['presence','Agent Presence','user','experts','Identity, activity, and the work in progress.'],['chat','Conversation','message','sessions','Every conversation carries its context.'],['canvas','Working Canvas','layout','artifacts','The output in focus, with its sources beside it.'],['proposals','Proposals','spark','proposals','Evidence-backed ideas, ready for review.'],['checks','Setup & Quality Checks','shield','checks','Readiness comes with evidence.'],['config','Expert Configuration','settings','configs','Shape the expert and review the exact change.'],['knowledge','Second Brain','brain','sources','Follow the connections behind what you know.'],['tasks','Tasks & Workstream','tasks','tasks','See dependencies before the next action.'],['artifacts','Artifacts','file','artifacts','Outputs, versions, and their origins.'],['console','Run Console','terminal','runs','The work as it happened.'],['changes','Changes & Approvals','check','intents','A clear before, after, and review trail.']].map(([id,title,icon,kind,description])=>({id,title,icon,kind,description}));
const C=window.FORGE_CONTRACTS,initial=structuredClone(window.FORGE_DATA),KEY='forge-connected-windows-v1';
let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}');}catch{}
let D=saved.data?.schema_version===initial.schema_version?saved.data:structuredClone(initial);
const params=new URLSearchParams(location.search),valid=(v,values,fallback)=>values.includes(v)?v:fallback;
const S={window:valid(params.get('window'),defs.map(d=>d.id),saved.window||'skills'),view:valid(params.get('view'),['gallery','preview','full'],'gallery'),scope:valid(params.get('scope'),['all',...D.prds.map(p=>p.prd_id)],'all'),design:valid(params.get('design'),['studio','editorial','precision','glass','contrast'],saved.design||'studio'),mode:valid(params.get('mode'),['light','dark'],saved.mode||'light'),selected:saved.selected||{},filters:saved.filters||{},tabs:saved.tabs||{},drafts:saved.drafts||{},context:saved.context||[],back:[],job:null,outcome:'ok'};
let toastTimer,runTimer;const views={};
const get=(r,path)=>path.split('.').reduce((v,k)=>v?.[k],r);
const id=(kind,r)=>r?.[C.keys[kind]],find=(kind,key)=>D[kind]?.find(r=>id(kind,r)===key),title=r=>r?.ui?.title||r?.title||r?.card_title||'Unlinked record';
const def=(windowId=S.window)=>defs.find(d=>d.id===windowId),all=kind=>D[kind]||[];
function scoped(kind){return all(kind).filter(r=>!r.ui?.scope||r.ui.scope==='shared'||S.scope==='all'||r.ui.scope===S.scope);}
function chosen(windowId=S.window){const kind=def(windowId).kind;const rows=scoped(kind);return rows.find(r=>id(kind,r)===S.selected[windowId])||rows[0]||null;}
function stateOf(r){return r?.ui?.state||r?.state||r?.status||r?.approval||'ready';}
const human=s=>({ok:'Success',error:'Error',running:'Running',cancelled:'Stopped',ready:'Ready',passed:'Passed',failed:'Failed',pending:'Pending',active:'Active',archived:'Archived',done:'Done',blocked:'Blocked',gated:'To review',queued:'Queued',approved:'Approved',denied:'Declined',unreviewed:'To review',gb_approved:'Approved',rejected:'Rejected','needs-review':'Needs review',PENDING_APPROVAL:'To review',APPROVED:'Approved',REFUSED:'Declined',EXECUTED:'Executed',current:'Current',stale:'Stale'})[s]||s;
function tone(s){return ['ok','passed','done','approved','gb_approved','APPROVED','current','ready'].includes(s)?'good':['error','failed','denied','rejected','REFUSED'].includes(s)?'bad':['running','active','queued'].includes(s)?'live':['gated','blocked','pending','PENDING_APPROVAL','needs-review','unreviewed','stale'].includes(s)?'warn':'muted';}
function badge(s,text=human(s)){return `<span class="badge ${tone(s)}">${icon(tone(s)==='good'?'check':tone(s)==='bad'?'error':tone(s)==='live'?'dots':tone(s)==='warn'?'clock':'minus')}${esc(text)}</span>`;}
function button(text,action,extra='',cls=''){return `<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;}
const openAttr=(kind,key,windowId='')=>`data-open-kind="${kind}" data-open-id="${esc(key)}" ${windowId?`data-open-window="${windowId}"`:''}`;
function chip(kind,key,label,windowId=''){const r=find(kind,key);return r?`<button class="link-chip" ${openAttr(kind,key,windowId)}>${icon(r.ui?.icon||'link')}${esc(label||title(r))}${icon('chevron')}</button>`:`<span class="badge">${icon('minus')}Unlinked ${esc(label||kind)}</span>`;}
function empty(text='No records in this view',detail='Try another workstream or clear the filters.'){return `<div class="empty">${icon('search')}<strong>${esc(text)}</strong>${esc(detail)}</div>`;}
function miniRow(kind,r,extra='',windowId=''){return `<button class="mini-row" ${openAttr(kind,id(kind,r),windowId)}><span class="category">${icon(r.ui?.icon||'file')}</span><span><strong>${esc(title(r))}</strong><small>${esc(extra||r.ui?.category||r.ui?.when||C.tables[kind])}</small></span>${badge(stateOf(r))}</button>`;}
function card(kind,r,extra='',windowId=S.window){return `<button class="card ${id(kind,r)===id(kind,chosen(windowId))?'selected':''}" data-select="${esc(id(kind,r))}" data-select-window="${windowId}"><div class="card-top"><span class="category">${icon(r.ui?.icon||'file')}</span>${badge(stateOf(r))}</div><strong>${esc(title(r))}</strong>${r.ui?.category?`<small>${esc(r.ui.category)}</small>`:''}${extra}</button>`;}
function metrics(values){return `<div class="metric-row">${values.map(([v,l])=>`<div class="metric"><b>${esc(v)}</b><small>${esc(l)}</small></div>`).join('')}</div>`;}
function flow(nodes,mini=false){return `<div class="flow ${mini?'mini-flow':''}">${nodes.map(([glyph,label,sub],i)=>`${i?icon('arrow'):''}<div class="flow-node"><span class="bubble">${icon(glyph)}</span><b>${esc(label)}</b>${sub?`<small>${esc(sub)}</small>`:''}</div>`).join('')}</div>`;}
function tabbar(windowId,values){const tab=S.tabs[windowId]||values[0][0];return `<div class="tabs" role="group" aria-label="${esc(def(windowId).title)} view">${values.map(([v,label])=>`<button data-tab="${v}" data-tab-window="${windowId}" aria-pressed="${tab===v}">${label}</button>`).join('')}</div>`;}
function filters(windowId,options=[]){const f=S.filters[windowId]||{};return `<div class="filterbar"><label class="search">${icon('search')}<input type="search" data-search="${windowId}" value="${esc(f.q||'')}" placeholder="Search ${esc(def(windowId).title.toLowerCase())}…" aria-label="Search ${esc(def(windowId).title)}"></label>${options.map(([key,label,values])=>`<label class="filter-label">${label}<select data-filter="${key}" data-filter-window="${windowId}"><option value="all">All ${label.toLowerCase()}</option>${values.map(v=>`<option value="${esc(v)}" ${f[key]===v?'selected':''}>${esc(human(v))}</option>`).join('')}</select></label>`).join('')}<button class="icon-button" data-clear-filters="${windowId}" title="Clear window filters" aria-label="Clear ${esc(def(windowId).title)} filters">${icon('refresh')}</button></div>`;}
function filtered(windowId,fields={}){const f=S.filters[windowId]||{},kind=def(windowId).kind;return scoped(kind).filter(r=>(!f.q||(title(r)+' '+id(kind,r)+' '+JSON.stringify(r.ui)).toLowerCase().includes(f.q.toLowerCase()))&&Object.entries(fields).every(([key,fn])=>!f[key]||f[key]==='all'||String(fn(r))===f[key]));}
function selectedFrom(windowId,rows){const r=rows.find(r=>id(def(windowId).kind,r)===S.selected[windowId])||rows[0]||null;if(r)S.selected[windowId]=id(def(windowId).kind,r);return r;}
function directEdges(kind,key){const output=[];for(const [from,field,to,type,label,source] of C.relations){if(from===kind){const value=get(find(kind,key),field);if(value)output.push({kind:to,id:value,type,label,source,via:`${C.tables[from]}.${field} → ${C.tables[to]}.${C.keys[to]}`});}if(to===kind)for(const r of all(from)){if(get(r,field)===key)output.push({kind:from,id:id(from,r),type,label:`${label} · referenced by`,source,via:`${C.tables[from]}.${field} → ${C.tables[to]}.${C.keys[to]}`});}}
 for(const e of D.uiLinks){if(e.from[0]===kind&&e.from[1]===key)output.push({kind:e.to[0],id:e.to[1],type:e.kind,label:e.label,source:'config',via:'Configuration contract / explicit UI reference'});if(e.to[0]===kind&&e.to[1]===key)output.push({kind:e.from[0],id:e.from[1],type:e.kind,label:e.label,source:'config',via:'Configuration contract / explicit UI reference'});}return output;}
function neighbors(kind,key){let edges=directEdges(kind,key);const expanded=[];for(const e of edges){if(['runArtifacts','routes','storage','sourceEvents'].includes(e.kind)){for(const n of directEdges(e.kind,e.id)){if(n.kind!==kind||n.id!==key)expanded.push({...n,label:e.kind==='runArtifacts'?'Run / output lineage':e.kind==='routes'?'Expert / skill binding':n.label});}}else expanded.push(e);}
 if(kind==='sources')for(const s of scoped('sessions'))if(s.ui.scope===find(kind,key)?.ui.scope)expanded.push({kind:'sessions',id:s.session_key,type:'demo',label:'Same workstream',source:'projection'});
 if(kind==='configs')for(const name of find(kind,key)?.skills||[])expanded.push({kind:'skills',id:name,type:'contract',label:'Pinned skill reference',source:'config'});
 if(kind==='skills')for(const c of all('configs'))if(c.skills.includes(key))expanded.push({kind:'configs',id:c.config_id,type:'contract',label:'Configuration binding',source:'config'});
 if(kind==='tasks')for(const taskId of find(kind,key)?.ui.depends_on||[])expanded.push({kind:'tasks',id:taskId,type:'demo',label:'Depends on',source:'projection'});
 const seen=new Set();return expanded.filter(e=>{const k=e.kind+':'+e.id;if(seen.has(k)||!find(e.kind,e.id))return false;seen.add(k);return true;});}
function related(windowId){const d=def(windowId),r=chosen(windowId);if(!r)return '';const links=neighbors(d.kind,id(d.kind,r));return `<aside class="relations"><h3>${icon('link')} Connected records</h3>${links.length?links.map(e=>{const n=find(e.kind,e.id);return `<button class="relation-row" ${openAttr(e.kind,e.id)}><span>${icon(n.ui?.icon||'file')}</span><span><strong>${esc(title(n))}</strong><small>${esc(e.label)}</small></span>${icon('chevron')}</button>`;}).join(''):'<p class="tiny muted">No linked records in this fixture.</p>'}<div class="record-stamp"><span>${esc(C.tables[d.kind])}</span><code>${esc(id(d.kind,r))}</code><button class="text-button" data-inspect-kind="${d.kind}" data-inspect-id="${esc(id(d.kind,r))}">Inspect fields & joins ${icon('source')}</button></div></aside>`;}
function persist(){try{localStorage.setItem(KEY,JSON.stringify({window:S.window,design:S.design,mode:S.mode,selected:S.selected,filters:S.filters,tabs:S.tabs,drafts:S.drafts,context:S.context,data:D}));}catch{}}
function url(){const q=new URLSearchParams({window:S.window,view:S.view,scope:S.scope,design:S.design,mode:S.mode});const r=chosen();if(r)q.set('record',id(def().kind,r));try{history.replaceState(null,'','?'+q);}catch{}}
function frame(windowId,mode){const d=def(windowId),view=views[windowId];const body=mode==='full'?view.full():view.preview(),r=chosen(windowId);return `<section class="window ${mode==="gallery"?"collection-window":mode}" data-window="${windowId}" aria-label="${esc(d.title)}"><header class="window-head"><span class="window-glyph">${icon(d.icon)}</span><h2>${d.title}</h2><div class="tools">${r?`<button class="icon-button" data-inspect-kind="${d.kind}" data-inspect-id="${esc(id(d.kind,r))}" title="Inspect connected data" aria-label="Inspect ${esc(d.title)} data">${icon('source')}</button>`:''}<button class="icon-button" data-expand="${windowId}" data-expand-mode="${mode}" aria-label="${mode==='full'?'Preview':'Expand'} ${esc(d.title)}">${icon(mode==='full'?'collapse':'expand')}</button></div></header><div class="window-body">${mode==='full'?`<div class="full-layout"><div class="primary-area">${body}</div>${related(windowId)}</div>`:body}</div><footer class="window-foot"><span>${icon('link')} ${r?neighbors(d.kind,id(d.kind,r)).length:0} related records</span><span>Demo data</span></footer></section>`;}
function render(){const focus=document.activeElement,attrs=['data-search','data-filter','data-input','data-config-field','data-select','data-action','data-tab'],attr=attrs.find(a=>focus?.hasAttribute?.(a));const value=attr?focus.getAttribute(attr):null;const selection=focus&&['INPUT','TEXTAREA'].includes(focus.tagName)?[focus.selectionStart,focus.selectionEnd]:null;const scroll=window.scrollY;
 document.body.dataset.mode=S.mode;document.body.dataset.design=S.design;$('theme-select').value=S.design;$('mode-toggle').innerHTML=icon(S.mode==='dark'?'sun':'moon');$('mode-toggle').setAttribute('aria-label',`Switch to ${S.mode==='dark'?'light':'dark'} mode`);$('scope').value=S.scope;
 $('window-nav').innerHTML=defs.map((d,i)=>`<button class="nav-window" data-nav="${d.id}" ${d.id===S.window&&S.view!=='gallery'?'aria-current="page"':''}>${icon(d.icon)}${d.title}<span class="nav-number">${String(i+1).padStart(2,'0')}</span></button>`).join('');
 document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===S.view)));$('scope-note').textContent=S.scope==='all'?'Shared records · One source per item':'Shared catalogs stay visible';
 $('breadcrumb').innerHTML=S.back.length?`<button class="text-button" data-action="back">${icon('back')} Back</button><span>${esc(def().title)}${chosen()?' / '+esc(title(chosen())):''}</span>`:'';
 $('content').innerHTML=S.view==='gallery'?`<div class="collection-intro"><div><span class="eyebrow">13 WINDOWS. ONE CONNECTED WORKSPACE.</span><h1>Every window has a purpose.</h1><p>Explore the previews. Expand any window to work with its connected records.</p></div><span class="collection-count">Studio / visual-first</span></div><div class="gallery">${defs.map(d=>frame(d.id,'gallery')).join('')}</div>`:S.view==='preview'?`<div class="preview-title"><span class="eyebrow">THE COMPACT WINDOW</span><h1>${def().title}</h1><p>${def().description}</p></div><div class="preview-wrap">${frame(S.window,'preview')}</div>`:frame(S.window,'full');
 if(attr){let target=Array.from(document.querySelectorAll(`[${attr}]`)).find(n=>n.getAttribute(attr)===value);if(!target&&attr==='data-action'&&value==='run')target=document.querySelector('[data-action="stop"]');if(target){target.focus({preventScroll:true});if(selection&&target.setSelectionRange&&target.type!=='number')try{target.setSelectionRange(...selection);}catch{}}}
 window.scrollTo(0,scroll);persist();url();
}
function toast(message){$('toast').hidden=false;$('toast').textContent=message;$('announcer').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
const targetWindow={skills:'skills',commands:'commands',experts:'presence',sessions:'chat',artifacts:'artifacts',tasks:'tasks',proposals:'proposals',sources:'knowledge',configs:'config',intents:'changes',runs:'console',checks:'checks',prds:'tasks'};
function navigate(windowId,key=null,push=true){if(!def(windowId))return;if(push)S.back.push(structuredClone({window:S.window,view:S.view,scope:S.scope,selected:S.selected,filters:S.filters}));S.window=windowId;S.view='full';if(key){const r=find(def(windowId).kind,key);if(r){S.selected[windowId]=key;if(r.ui?.scope&&r.ui.scope!=='shared'&&S.scope!=='all'&&S.scope!==r.ui.scope){S.scope=r.ui.scope;toast('Workstream updated to follow the linked record.');}}S.filters[windowId]={};}render();window.scrollTo(0,0);$('main').focus({preventScroll:true});}
function open(kind,key,windowId){const target=windowId||targetWindow[kind];if(kind==='prds'){S.scope=key;navigate('tasks');return;}if(target)navigate(target,key);else inspect(kind,key);}
function inspect(kind,key){const r=find(kind,key);if(!r)return;const edges=directEdges(kind,key);$('inspect-title').textContent=title(r);$('inspect-content').innerHTML=`<div class="note-box">${esc(C.tables[kind])} · <code>${esc(key)}</code><br>Projection fields keep their source names. <code>ui</code> fields are design-only. All values shown here are fixtures.</div><div class="contract-scroll"><table class="contract-table"><thead><tr><th>Connected record</th><th>Relationship</th><th>Contract</th></tr></thead><tbody>${edges.map(e=>`<tr><td>${chip(e.kind,e.id)}<br><code>${esc(e.via||'UI association')}</code></td><td>${esc(e.type)}</td><td>${sourceLink(e.source)}</td></tr>`).join('')||'<tr><td colspan="3">No direct edges for this record.</td></tr>'}</tbody></table></div><details class="spaced"><summary>Record fields</summary><pre class="inspector-json">${esc(JSON.stringify(r,null,2))}</pre></details>`;if(!$('inspect-dialog').open)$('inspect-dialog').showModal();}
function sourceLink(source){const s=C.sources[source];return s?`<a href="../../${s.path}" target="_blank" rel="noopener">${esc(s.path.split('/').pop())}</a><small> · ${esc(s.lines)}</small>`:'UI fixture';}
function buildDialogs(){const positions=[['knowledge',30,35],['proposals',340,35],['tasks',650,35],['skills',30,160],['console',340,160],['artifacts',650,160],['presence',30,285],['chat',340,285],['changes',650,285]];
 $('map-content').innerHTML=`<svg class="spine-svg" viewBox="0 0 900 390" role="img" aria-label="Sources connect to proposals and tasks; skills connect to runs and outputs; sessions and approval evidence connect the workspace" style="width:100%;height:auto"><defs><marker id="arrowhead" markerWidth="6" markerHeight="6" refX="5" refY="3" orient="auto"><path d="M0 0 6 3 0 6" fill="var(--accent)"/></marker></defs>${[[270,73,340,73],[580,73,650,73],[270,198,340,198],[580,198,650,198],[270,323,340,323],[580,323,650,323],[460,110,460,160],[770,110,770,160],[460,235,460,285]].map(p=>`<path d="M${p[0]} ${p[1]} L${p[2]} ${p[3]}" stroke="var(--accent)" stroke-width="1.5" fill="none" marker-end="url(#arrowhead)"/>`).join('')}${positions.map(([w,x,y])=>`<g><rect x="${x}" y="${y}" width="240" height="75" rx="10" fill="var(--canvas)" stroke="var(--line)"/><text x="${x+16}" y="${y+29}" fill="var(--text)" font-family="Inter,sans-serif" font-size="14">${def(w).title.replace('&','&amp;')}</text><text x="${x+16}" y="${y+51}" fill="var(--muted)" font-family="Inter,sans-serif" font-size="10">${C.tables[def(w).kind]}</text></g>`).join('')}</svg><p class="tiny">Arrows show navigation paths. Use the record inspector for the exact join type and source contract.</p><div class="schema-map">${defs.map(d=>`<button data-nav="${d.id}">${icon(d.icon)}<strong>${d.title}</strong><small>${esc(C.tables[d.kind])}</small></button>`).join('')}</div><div class="note-box"><b>FK</b>: declared in a committed migration. <b>Conditional FK</b>: migration adds it only if its dependency exists. <b>Reference</b>: matching values without a verified constraint. <b>Contract</b>: typed configuration reference. <b>Demo</b>: explicit UI association. Deployment and live FK presence were not queried.</div><details><summary>Source contracts and proposed UI joins</summary><div class="contract-scroll"><table class="contract-table"><thead><tr><th>From</th><th>To</th><th>Type</th><th>Source</th></tr></thead><tbody>${C.relations.map(([a,f,b,t,,s])=>`<tr><td><code>${C.tables[a]}.${f}</code></td><td><code>${C.tables[b]}.${C.keys[b]}</code></td><td>${t}</td><td>${sourceLink(s)}</td></tr>`).join('')}</tbody></table></div></details>`;
 const rules=[['layout','Two sizes, one identity','A preview for awareness. A full workspace for decisions. Selection and drafts stay with you.'],['eye','Visuals carry the meaning','Flows, rings, maps, boards, previews, and diffs match the work in each window.'],['link','Relationships are actionable','Open the producing run, source, session, task, or review directly from the record.'],['search','Filters match the data','Workstream, state, type, owner, route, and format reveal the records you need.'],['check','One status, everywhere','A demo run or review updates all connected views. Color is always paired with an icon or label.'],['source','Evidence stays close','Inspect identifiers and join types on demand. Never label a proposed UI connection as a proven FK.']];$('guide-content').innerHTML=`<div class="guide-grid">${rules.map(([i,h,p])=>`<article class="guide-card">${icon(i)}<h4>${h}</h4><p>${p}</p></article>`).join('')}</div><p class="note-box">File Commands established the approved direction. This collection extends it to all 13 windows. Studio stays the default; light/dark mode and the four alternative treatments remain independent of your selections.</p><div class="link-chips">${['shield','graph','spark','file','clock','user','link','source'].map(i=>`<span class="badge">${icon(i)}${i}</span>`).join('')}</div>`;}
function download(name,value){const blob=new Blob([typeof value==='string'?value:JSON.stringify(value,null,2)],{type:typeof value==='string'?'text/plain':'application/json'}),href=URL.createObjectURL(blob),a=document.createElement('a');a.href=href;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(href),1000);}
function run(skillName,opts={}){if(S.job){toast('One demo job is already running. Open Run Console to follow it.');return;}const skill=find('skills',skillName)||D.skills[3],key=crypto.randomUUID();const scope=opts.scope||((S.scope==='all'||S.scope==='shared')?'prd_demo_health':S.scope);const session=scoped('sessions').find(s=>s.ui.scope===scope)||D.sessions[0];const r={run_id:key,skill_name:skill.skill_name,parent_run_id:null,trace_id:session.trace_id,status:'running',started_at:new Date().toISOString(),elapsed_ms:0,ui:{title:opts.title||skill.ui.title,icon:skill.ui.icon,scope,command:opts.command||skill.skill_name,session_key:session.session_key,task_id:session.kanban_task_id,exit:null,lines:[['system','SIMULATION · No process started.'],['stdout','Loading the selected context…']]}};D.runs.unshift(r);S.job=key;S.selected.console=key;const outcome=S.outcome;let step=0;render();toast('Demo run started.');runTimer=setInterval(()=>{step++;r.elapsed_ms=step*900;r.ui.lines.push([step===3&&outcome==='error'?'stderr':'stdout',step===1?'Context loaded.':step===2?'Processing sample records…':step===3&&outcome==='error'?'Sample error: connection unavailable.':'Result assembled.']);if(step===4){clearInterval(runTimer);S.job=null;r.status=outcome;r.ended_at=new Date().toISOString();r.ui.exit=outcome==='ok'?0:1;r.ui.lines.push(['system','Exit '+r.ui.exit]);if(outcome==='ok'){const aid='art_demo_'+key.slice(0,8);D.artifacts.unshift({artifact_id:aid,artifact_family_id:aid,version_label:'v1',is_latest:true,lifecycle:'active',approval:'unreviewed',file_ext:'json',filename:'demo-run-result.json',artifact_kind:'receipt',source_artifact_id:scope==='prd_demo_health'?'src_health':'src_transcript',task_id:session.kanban_task_id,prd_id:scope,run_id:key,bytes:300,ui:{title:r.ui.title+' / result',icon:'file',scope,subtitle:'Demo run receipt',summary:'Completed locally in the design preview.',sections:['Context loaded','Recipe completed','Receipt captured']}});D.runArtifacts.push({link_id:'link_'+key,artifact_id:aid,skill_run_id:key,run_kind:'skill',relationship:'produced'});if(opts.checks)D.checks.forEach((c,i)=>{c.state=i===7?'pending':'passed';c.run_id=key;});}toast('Demo run '+human(outcome).toLowerCase()+'. Connected views updated.');}render();},900);}
function stop(){if(!S.job)return;const r=find('runs',S.job);clearInterval(runTimer);r.status='cancelled';r.ended_at=new Date().toISOString();r.ui.lines.push(['system','Stopped by operator. Partial output retained.']);S.job=null;render();toast('Demo run stopped.');}
function start(){for(const r of D.runs)if(r.status==='running'){r.status='cancelled';r.ui.lines.push(['system','Demo ended on page reload.']);}if(params.get('record')&&find(def().kind,params.get('record')))S.selected[S.window]=params.get('record');buildDialogs();render();
 document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;
 if(d.close){$(d.close).close();return;}if(d.nav){document.querySelectorAll('dialog[open]').forEach(x=>x.close());navigate(d.nav);return;}if(d.view){S.view=d.view;render();return;}if(d.expand){S.window=d.expand;S.view=d.expandMode==='full'?'preview':'full';render();window.scrollTo(0,0);return;}
 if(d.openKind){document.querySelectorAll('dialog[open]').forEach(x=>x.close());open(d.openKind,d.openId,d.openWindow);return;}if(d.inspectKind){inspect(d.inspectKind,d.inspectId);return;}
 if(d.select){S.selected[d.selectWindow]=d.select;render();return;}if(d.tab){S.tabs[d.tabWindow]=d.tab;render();return;}if(d.clearFilters){S.filters[d.clearFilters]={};render();return;}
 if(d.action==='back'){const old=S.back.pop();if(old){Object.assign(S,old);render();}return;}if(d.action==='stop'){stop();return;}if(d.action)views[d.window||S.window]?.action?.(d.action,b);
 });
 document.addEventListener('input',e=>{const d=e.target.dataset;if(d.search){S.filters[d.search]??={};S.filters[d.search].q=e.target.value;render();}if(d.input){S.drafts[d.input]=e.target.value;persist();}if(d.configField){S.drafts.config??={};S.drafts.config[d.configField]=e.target.value;persist();}});
 document.addEventListener('change',e=>{const d=e.target.dataset;if(d.filter){S.filters[d.filterWindow]??={};S.filters[d.filterWindow][d.filter]=e.target.value;render();}if(d.configField){S.drafts.config??={};S.drafts.config[d.configField]=e.target.value;persist();}if(d.selectRecord){S.selected[d.selectRecord]=e.target.value;render();}if(d.setting){S[d.setting]=e.target.value;render();}});
 $('scope').addEventListener('change',e=>{S.scope=e.target.value;render();});$('theme-select').addEventListener('change',e=>{S.design=e.target.value;render();});$('mode-toggle').addEventListener('click',()=>{S.mode=S.mode==='dark'?'light':'dark';render();});$('map-open').addEventListener('click',()=>$('map-dialog').showModal());$('guide-open').addEventListener('click',()=>$('guide-dialog').showModal());$('export-data').addEventListener('click',()=>download('forge-connected-demo.json',{schema_version:D.schema_version,demo:true,runtime_authorized:false,data:D,review:{window:S.window,scope:S.scope,design:S.design,mode:S.mode}}));
 document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')&&S.view==='full'){S.view='preview';render();}});
}
return {$,esc,icon,defs,def,C,get,id,find,title,all,scoped,chosen,stateOf,human,tone,badge,button,chip,empty,miniRow,card,metrics,flow,tabbar,filters,filtered,selectedFrom,neighbors,directEdges,render,navigate,open,inspect,toast,download,run,stop,start,views,S,get D(){return D;}};
})();
