(()=>{
'use strict';
const F=window.Forge,{esc,icon,badge,chip,button,miniRow,metrics,flow,card,filters,tabbar,empty}=F;
const S=F.S,view=F.views,D=F.D;
const uid=()=>crypto.randomUUID().slice(0,8),act=(text,name,w,extra='',cls='')=>button(text,name,`data-window="${w}" ${extra}`,cls);
const hero=(r,subtitle,action='')=>`<div class="hero-row"><span class="category">${icon(r.ui?.icon||'file')}</span><div class="grow"><h1>${esc(F.title(r))}</h1><p>${esc(subtitle)}</p></div>${action?`<div class="hero-action">${action}</div>`:''}</div>`;
const meta=(a,b)=>`<div class="card-meta"><span>${icon(a[0])}${esc(a[1])}</span><span>${icon(b[0])}${esc(b[1])}</span></div>`;
const line=(k,v)=>`<div class="detail-line"><span>${esc(k)}</span><strong>${esc(v)}</strong></div>`;
const select=(w,rows,label=F.def(w).title)=>`<label class="field">${esc(label)}<select data-select-record="${w}" aria-label="${esc(label)}">${rows.map(r=>`<option value="${esc(F.id(F.def(w).kind,r))}" ${F.id(F.def(w).kind,r)===F.id(F.def(w).kind,F.chosen(w))?'selected':''}>${esc(F.title(r))}${r.version_label?' / '+r.version_label:''}</option>`).join('')}</select></label>`;
const miniAction=(text,w,note='')=>`<div class="mini-action"><small>${note}</small><button class="primary" data-expand="${w}" data-expand-mode="preview">${text}${icon('expand')}</button></div>`;
const skillRuns=r=>D.runs.filter(x=>x.skill_name===r.skill_name),latestArtifacts=()=>F.scoped('artifacts').filter(a=>a.is_latest);
const runArtifacts=r=>D.runArtifacts.filter(l=>l.skill_run_id===r.run_id).map(l=>F.find('artifacts',l.artifact_id)).filter(Boolean);
const pulse=runs=>`<span class="pulse" role="img" aria-label="${esc(runs.map(r=>F.human(r.status)).join(', ')||'No runs')}">${runs.slice(0,5).reverse().map(r=>`<i class="${r.status}" title="${F.human(r.status)}"></i>`).join('')}</span>`;
function thumb(a){return `<div class="artifact-thumb">${icon(a.ui.icon)}<span class="format">${a.file_ext.toUpperCase()} / ${a.version_label}</span><i class="line short"></i><i class="line"></i><i class="line"></i>${a.file_ext==='json'?'<span class="thumb-bars"><i style="height:14px"></i><i style="height:24px"></i><i style="height:35px"></i></span>':''}</div>`;}
function documentView(a,mini=false){return `<article class="document ${mini?'mini-document':''}"><span class="eyebrow">${esc(a.artifact_kind)} · ${a.version_label} · DEMO</span><h2>${esc(a.ui.summary)}</h2><div class="doc-rule"></div><p>${esc(a.ui.subtitle)}</p><div class="doc-sections">${(a.ui.sections||[]).map((t,i)=>`<div class="doc-section">${icon(['shield','link','eye'][i%3])}<b>${esc(t)}</b><p>${['A bounded task with a visible result.','Keep the evidence alongside the finding.','Surface uncertainty before the next action.'][i%3]}</p></div>`).join('')}</div></article>`;}
function logs(r,mini=false){if(!r)return empty('No run selected');const stream=S.tabs.consoleStream||'all';return `<div class="terminal ${mini?'mini-terminal':''}" role="region" aria-label="Sample terminal output">${r.ui.lines.filter(l=>mini||stream==='all'||l[0]===stream).map(([type,text],i)=>`<div class="terminal-line ${type}">${mini?'':`<span class="line-no">${String(i+1).padStart(2,'0')}</span>`}<span class="${type}">${type}</span><span class="line-text">${esc(text)}</span></div>`).join('')||'<p class="tiny">No messages in this stream.</p>'}</div>`;}

view.skills={
 preview(){const rows=F.scoped('skills').slice(0,3);return `<div class="row between"><span class="eyebrow">CAPABILITIES</span><span class="badge">${F.scoped('skills').length} bound skills</span></div>${flow([['input','Source'],['spark','Skill'],['file','Output']],true)}<div class="mini-list">${rows.slice(0,2).map(r=>miniRow('skills',r,r.ui.input+' → '+r.ui.output)).join('')}</div>${miniAction('Explore skills','skills','Inputs → capabilities → results')}`;},
 full(){const rows=F.filtered('skills',{category:r=>r.ui.category,status:F.stateOf});const r=F.selectedFrom('skills',rows);return filters('skills',[['category','Category',['Research','Publishing','Quality','Context']],['status','State',['ready','needs-review']]])+(r?`<div class="cards">${rows.map(s=>card('skills',s,meta(['input',s.ui.input],['history',skillRuns(s).length+' runs']),'skills')).join('')}</div><div class="spaced">${hero(r,r.ui.input+' → '+r.ui.output,act(icon('message')+' Use in conversation','use','skills','','primary'))}${flow([['input',r.ui.input],['spark',r.ui.title],['file',r.ui.output]])}${metrics([[skillRuns(r).length,'Related runs'],[D.configs.filter(c=>c.skills.includes(r.skill_name)).length,'Configurations'],[skillRuns(r).flatMap(runArtifacts).length,'Linked outputs']])}<div class="split"><div class="subpanel"><h4>Binding</h4>${line('Expert','YouTube Intelligence')}${line('Category',r.ui.category)}${line('Policy',D.routes.find(x=>x.skill_name===r.skill_name)?.execution_policy||'Reference')}${line('State',F.human(r.ui.state))}</div><div><div class="section-label">Recent runs</div><div class="mini-list">${skillRuns(r).map(x=>miniRow('runs',x,(x.elapsed_ms/1000).toFixed(1)+' seconds')).join('')||empty('No runs yet','Use this skill in a demo conversation.')}</div></div></div></div>`:empty());},
 action(name){if(name==='use'){const r=F.chosen('skills');S.context=S.context.filter(c=>c.kind!=='skills');S.context.push({kind:'skills',id:r.skill_name});F.navigate('chat');F.toast('Skill added to the conversation context.');}}
};
view.commands={
 preview(){const rows=F.scoped('commands').filter(r=>['health','prime','question'].includes(r.id)),r=F.chosen('console');return `<div class="row between"><span class="eyebrow">QUICK COMMANDS</span><span class="badge">19 recipes</span></div><div class="mini-list spaced">${rows.map(c=>miniRow('commands',c,c.parameters?'Takes input':'Ready to run')).join('')}</div><div class="row between spaced">${badge(r?.status||'ready')}<small>${r?(r.elapsed_ms/1000).toFixed(1)+'s':'No recent run'}</small></div>${miniAction('Open commands','commands','Approved visual pattern')}`;},
 full(){const rows=F.filtered('commands',{category:r=>r.ui.category}),r=F.selectedFrom('commands',rows);if(!r)return filters('commands')+empty();const matches=F.scoped('runs').filter(x=>x.ui.command==='just '+r.id);const last=matches[0];const argument=S.drafts['command:'+r.id]||'';return filters('commands',[['category','Category',['Checks','Input','Recipes']]])+`<div class="split"><div class="mini-list" style="max-height:640px;overflow:auto">${rows.map(c=>`<button class="mini-row" data-select="${c.id}" data-select-window="commands"><span class="category">${icon('terminal')}</span><span><strong>${esc(c.ui.title)}</strong><small>just ${c.id}</small></span>${r.id===c.id?icon('check'):''}</button>`).join('')}</div><div>${hero(r,'Inspect the recipe, then follow its output.',S.job?act(icon('stop')+' Stop','stop','commands','','danger'):act(icon('play')+' Run Now','run','commands','','primary'))}${r.parameters?`<label class="field">${r.parameters.includes('=')?'Optional':'Required'} input<input data-input="command:${r.id}" value="${esc(argument)}" ${r.parameters.includes('=')?'':'required'} placeholder="${r.id==='graph'?'--freshness':'Describe the request…'}"></label>`:''}<div class="note-box mono">$ just ${esc(r.id)} ${esc(argument)}</div>${flow([['folder','Context'],['terminal',r.id],['check',last?F.human(last.status):'Not run'],['file','Output']])}${last?metrics([[F.human(last.status),'Latest run'],[(last.elapsed_ms/1000).toFixed(1)+'s','Duration'],[last.ui.exit??'—','Exit code']])+logs(last):empty('Ready for its first run','Run Now creates a local demo run and linked result.') }<div class="link-chips">${last?chip('runs',last.run_id,'Open full run'):''}</div><details class="spaced"><summary>Recipe source</summary><pre class="inspector-json">${esc(r.source)}</pre></details><p class="tiny spaced">Source recipe text is preserved from the approved snapshot. Execution is simulated.</p></div></div>`;},
 action(name){if(name==='run'){const r=F.chosen('commands'),input=document.querySelector(`[data-input="command:${r.id}"]`);if(input&&!input.reportValidity())return;const skill=r.id==='prime'?D.skills[4]:r.id==='question'?D.skills[1]:D.skills[3];F.run(skill.skill_name,{title:r.ui.title,command:'just '+r.id});}}
};
view.presence={
 preview(){const expert=F.chosen('presence');return `<div class="avatar-stage"><div class="avatar-ring"><img src="../nexus-forge-window-preview-2026-09-18/assets/youtube-avatar.jpg" alt="YouTube Intelligence configured avatar"><span class="avatar-state">${badge('active','Demo presence')}</span></div></div><div class="presence-caption"><strong>${expert.display_name}</strong><small>Research & synthesis · Hermes profile</small></div><div class="mini-metrics row between"><div><b>${F.scoped('sessions').length}</b><small>sessions</small></div><div><b>${F.scoped('tasks').filter(t=>t.status!=='done').length}</b><small>open tasks</small></div><div><b>${S.job?1:0}</b><small>running now</small></div></div>${miniAction('Open presence','presence')}`;},
 full(){const r=F.chosen('presence'),sessions=F.filtered('chat',{status:r=>r.status});return `<div class="presence-large"><div><div class="avatar-stage"><div class="avatar-ring"><img src="../nexus-forge-window-preview-2026-09-18/assets/youtube-avatar.jpg" alt="Configured YouTube expert avatar"><span class="avatar-state">${badge(S.job?'running':'active',S.job?'Demo running':'Demo presence')}</span></div></div><div class="presence-caption"><strong>${r.display_name}</strong><small>${r.ui.role}</small></div></div><div>${hero(r,'The expert, its runtime identity, and its current work.')}${line('Profile',r.ui.profile)}${line('Harness','Hermes')}${line('Provider',D.configs[0].ui.provider)}${line('Runtime verification','Not connected in this preview')}<svg class="heartbeat" viewBox="0 0 500 45" role="img" aria-label="Illustrative activity signal"><path d="M0 24H55l6-7 7 17 10-28 10 32 9-14h60l6-7 6 14 10-25 10 30 9-12h75l6-9 7 21 10-30 10 29 8-11H500"/></svg><small class="tiny">Illustrative activity signal</small></div></div>${metrics([[F.scoped('sessions').length,'Sessions in scope'],[F.scoped('runs').filter(r=>r.status==='ok').length,'Successful runs'],[F.scoped('tasks').filter(t=>t.status!=='done').length,'Open tasks']])}<div class="section-label">Linked sessions</div>${filters('chat',[['status','State',['active','error','archived']]])}<div class="cards">${sessions.map(s=>`<button class="card" data-open-kind="sessions" data-open-id="${s.session_key}"><div class="card-top"><span class="category">${icon('message')}</span>${badge(s.status)}</div><strong>${esc(s.title)}</strong>${meta(['clock',s.ui.when],['message',D.messages.filter(m=>m.session_key===s.session_key).length+' messages'])}</button>`).join('')||empty()}</div>`;}
};
view.chat={
 preview(){const r=F.chosen('chat');if(!r)return empty();const msgs=D.messages.filter(m=>m.session_key===r.session_key),m=msgs.at(-1);return `<div class="row between"><span class="eyebrow">${esc(r.title)}</span>${badge(r.status)}</div><div class="mini-message"><small>YOUTUBE INTELLIGENCE · DEMO</small>${esc(m?.content||'Start a focused conversation with the expert.')}</div><div class="link-chips">${m?.ui.artifact_id?chip('artifacts',m.ui.artifact_id,'Open brief','canvas'):chip('sources','src_decision','Source policy')}</div>${miniAction('Continue','chat',msgs.length+' messages · Context attached')}`;},
 full(){const rows=F.filtered('chat',{status:r=>r.status}),r=F.selectedFrom('chat',rows);return filters('chat',[['status','State',['active','error','archived']]])+(r?`<div class="chat-shell"><aside class="session-list">${rows.map(s=>`<button class="mini-row ${s.session_key===r.session_key?'selected':''}" data-select="${s.session_key}" data-select-window="chat"><span class="category">${icon('message')}</span><span><strong>${esc(s.title)}</strong><small>${esc(s.ui.when)}</small></span></button>`).join('')}</aside><div>${hero(r,'A conversation with its context and outputs.')}<div class="context-bar"><span class="badge">${icon('layers')}Context</span>${chip('sources','src_decision','Citation policy')}${S.context.map(c=>chip(c.kind,c.id)).join('')}</div><div class="messages" aria-label="Conversation messages">${D.messages.filter(m=>m.session_key===r.session_key).map(m=>`<article class="message ${m.role}"><span class="speaker">${m.role==='user'?'YOU':'YOUTUBE INTELLIGENCE · DEMO'}</span><p>${esc(m.content)}</p>${m.ui.artifact_id?`<div class="link-chips">${chip('artifacts',m.ui.artifact_id,null,'canvas')}</div>`:''}${m.ui.run_id?`<div class="link-chips">${chip('runs',m.ui.run_id,'View execution')}</div>`:''}</article>`).join('')||empty('No messages yet','Start this local demonstration conversation.')}</div><div class="composer"><label class="grow"><span class="sr-only">Message to demo expert</span><textarea data-input="chat:${r.session_key}" placeholder="Ask about this workstream…" maxlength="2000">${esc(S.drafts['chat:'+r.session_key]||'')}</textarea></label>${act(icon('send'),'send','chat',`data-session="${r.session_key}" aria-label="Send demo message"`,'primary')}</div><p class="tiny spaced">Demo replies are local examples. No message is sent to an agent.</p></div></div>`:empty());},
 action(name,b){if(name==='send'){const key=b.dataset.session,r=F.find('sessions',key),text=(S.drafts['chat:'+key]||'').trim();if(!text){F.toast('Write a message first.');return;}D.messages.push({message_key:'msg_'+uid(),session_key:key,role:'user',content:text,ui:{title:'Your message',icon:'message',scope:r.ui.scope}});const art=F.scoped('artifacts').find(a=>a.ui.scope===r.ui.scope&&a.is_latest);D.messages.push({message_key:'msg_'+uid(),session_key:key,role:'assistant',content:'Demo reply: I’ve kept the selected context with this conversation. The related result is linked here for review.',ui:{title:'Demo reply',icon:'spark',scope:r.ui.scope,...(art?{artifact_id:art.artifact_id}:{})}});S.drafts['chat:'+key]='';F.render();F.toast('Demo conversation updated.');}}
};
view.canvas={
 preview(){const a=F.chosen('canvas');return a?documentView(a,true)+miniAction('Open canvas','canvas',a.version_label+' · Source-linked'):empty();},
 full(){const rows=F.filtered('canvas',{type:a=>a.artifact_kind}),a=F.selectedFrom('canvas',rows);if(!a)return filters('canvas')+empty();const family=D.artifacts.filter(x=>x.artifact_family_id===a.artifact_family_id);const tab=S.tabs.canvas||'document';return filters('canvas',[['type','Type',['report','dataset','receipt']]])+`<div class="row between wrap">${select('canvas',rows,'Document / version')}${act(icon('download')+' Download','download','canvas')}</div><div class="spaced">${tabbar('canvas',[['document','Document'],['compare','Compare versions'],['sources','Sources']])}</div>${tab==='document'?documentView(a):tab==='compare'?family.length>1?`<div class="compare-docs">${family.slice(0,2).map(x=>documentView(x)).join('')}</div>`:empty('One version available','No comparison can be made yet.'):`<div class="network"><div class="network-column"><div class="network-node">${icon('message')}<strong>Source evidence</strong>${chip('sources',a.source_artifact_id)}</div></div><div class="network-node center">${icon('file')}<strong>${esc(F.title(a))}</strong><small>${a.version_label}</small></div><div class="network-column"><div class="network-node">${icon('terminal')}<strong>Produced by</strong>${chip('runs',a.run_id)}</div></div></div>`}<label class="field document-note">Review note<textarea data-input="note:${a.artifact_id}" rows="2" placeholder="Keep a note with this version…">${esc(S.drafts['note:'+a.artifact_id]||'')}</textarea></label><div class="mini-action"><small>Notes save locally with this artifact version.</small>${chip('artifacts',a.artifact_id,'Inspect artifact')}</div>`;},
 action(name){if(name==='download'){const a=F.chosen('canvas');F.download(a.filename.replace(/\.[^.]+$/,'.preview.json'),{demo:true,artifact:a,review_note:S.drafts['note:'+a.artifact_id]||''});}}
};
view.proposals={
 preview(){const rows=F.scoped('proposals');return `<div class="row between"><span class="eyebrow">IDEAS WITH EVIDENCE</span>${badge('gated',rows.filter(p=>p.state==='gated').length+' to review')}</div><div class="proposal-steps"><span class="done"></span><span class="done"></span><span class="current"></span><span></span></div><div class="mini-list">${rows.slice(0,2).map(p=>miniRow('proposals',p,p.ui.impact)).join('')}</div>${miniAction('Review proposals','proposals','Source → idea → review')}`;},
 full(){const rows=F.filtered('proposals',{status:p=>p.state,route:p=>p.workflow_route}),r=F.selectedFrom('proposals',rows);return filters('proposals',[['status','State',['gated','blocked','approved','denied']],['route','Route',['research','planning','hotfix']]])+(r?`<div class="proposal-list">${rows.map(p=>card('proposals',p,meta(['link',p.source_type.replaceAll('_',' ')],['box',p.ui.impact]),'proposals')).join('')}</div><div class="spaced">${hero(r,r.ui.why,r.ui.intent_id?chip('intents',r.ui.intent_id,'Review exact change'):chip('tasks',r.task_id,'Inspect blocker'))}${flow([['file','Source event'],['spark','Proposal'],[r.state==='blocked'?'lock':'eye',F.human(r.state)],['tasks','Work item']])}<div class="split"><div class="subpanel"><h4>Scope</h4>${line('Impact',r.ui.impact)}${line('Route',r.workflow_route)}${line('State',F.human(r.state))}</div><div class="subpanel"><h4>${r.state==='blocked'?'What is blocking this?':'Evidence & next step'}</h4><p>${esc(r.blocker_next_safe_action||'Review the exact result or configuration change before the next step.')}</p><div class="link-chips">${chip('sourceEvents',r.source_event_id,'Source event')}${r.task_id?chip('tasks',r.task_id,'Related task'):''}${r.ui.intent_id?chip('intents',r.ui.intent_id,'Approval review'):''}</div></div></div></div>`:empty());}
};
function readiness(mini=false){const checks=F.scoped('checks'),pass=checks.filter(c=>c.state==='passed').length,failed=checks.filter(c=>c.state==='failed').length;return `<div class="readiness"><div class="donut"><svg viewBox="0 0 120 120" aria-hidden="true"><circle cx="60" cy="60" r="48"/><circle class="value" cx="60" cy="60" r="48" stroke-dasharray="${302*pass/(checks.length||1)} 302"/></svg><div class="donut-label"><b>${pass}<span class="muted" style="font-size:16px"> / ${checks.length}</span></b><small>CHECKS PASSED</small></div></div><div class="readiness-legend"><span>${badge('passed',pass+' passed')}</span><span>${badge('failed',failed+' failed')}</span><span>${badge('pending',(checks.length-pass-failed)+' pending')}</span></div></div>`;}
view.checks={
 preview(){const rows=F.scoped('checks');return readiness(true)+`<div class="mini-list">${rows.filter(c=>c.state!=='passed').slice(0,2).map(c=>miniRow('checks',c,c.ui.category)).join('')}</div>${miniAction('Review readiness','checks','Configured ≠ verified')}`;},
 full(){const rows=F.filtered('checks',{status:c=>c.state,category:c=>c.ui.category}),r=F.selectedFrom('checks',rows);return filters('checks',[['status','State',['passed','failed','pending']],['category','Category',['Profile','Bindings','Runtime']]])+`<div class="row between wrap"><div>${readiness()}</div><div>${act(icon('play')+' Run demo checks','run','checks',S.job?'disabled':'','primary')}<p class="tiny spaced">Live activation remains a separate check.</p></div></div><div class="check-list">${rows.map(c=>`<button class="check-item ${r?.check_id===c.check_id?'selected':''}" data-select="${c.check_id}" data-select-window="checks"><span class="${F.tone(c.state)}">${icon(c.state==='passed'?'check':c.state==='failed'?'error':'clock')}</span><span>${esc(c.ui.title)}</span>${badge(c.state)}</button>`).join('')||empty()}</div>${r?`<div class="subpanel spaced"><h4>${esc(r.ui.title)} / evidence</h4>${line('Profile',r.profile)}${line('Result',F.human(r.state))}<div class="link-chips">${chip('runs',r.run_id,'Verification run')}${r.ui.source_id?chip('sources',r.ui.source_id):chip('configs',D.configs[0].config_id,'Configuration')}</div></div>`:''}`;},
 action(name){if(name==='run')F.run(D.skills[3].skill_name,{title:'Readiness inspection',command:'just health',scope:'prd_demo_health',checks:true});}
};
function configValue(field){return S.drafts.config?.[field]??D.configs[0].ui[field];}
view.config={
 preview(){const c=D.configs[0];return `<div class="row between"><span class="eyebrow">EXPERT BLUEPRINT</span><span class="badge">v${c.version} · Source</span></div><div class="config-mini-grid spaced">${[['spark',c.ui.model,'Model'],['shield','Manual','Approval'],['video',c.ui.video_cap+' videos','Scan cap'],['layers',c.skills.length+' skills','Bindings']].map(([i,v,l])=>`<div class="config-mini">${icon(i)}<b>${esc(v)}</b><small>${l}</small></div>`).join('')}</div>${miniAction('Edit configuration','config','Draft → diff → review')}`;},
 full(){const c=D.configs[0];return hero(c,'Source settings and a separately saved draft.',act(icon('check')+' Save review draft','save','config','','primary'))+`<div class="config-grid"><section class="config-tile"><h4>${icon('spark')} Identity & model</h4><label class="field">Purpose<textarea rows="3" data-config-field="purpose">${esc(configValue('purpose'))}</textarea></label><label class="field">Model<select data-config-field="model">${['gpt-5.6-sol','gpt-6-sol'].map(x=>`<option ${configValue('model')===x?'selected':''}>${x}</option>`).join('')}</select></label>${line('Provider',c.ui.provider)}</section><section class="config-tile"><h4>${icon('video')} Operating limits</h4><label class="field">Video cap<input type="number" min="1" max="50" required data-config-field="video_cap" value="${esc(configValue('video_cap'))}"></label><label class="field">Scan window / days<input type="number" min="1" max="30" required data-config-field="scan_days" value="${esc(configValue('scan_days'))}"></label><label class="field">Maximum turns<input type="number" min="1" max="200" required data-config-field="max_turns" value="${esc(configValue('max_turns'))}"></label></section><section class="config-tile"><h4>${icon('shield')} Controls</h4>${line('Approval policy','Manual')}${line('Runtime profile',c.fleet_profile)}<div class="link-chips">${c.ui.tools.map(t=>`<span class="badge">${icon('check')}${t}</span>`).join('')}</div></section><section class="config-tile"><h4>${icon('link')} Skill bindings</h4><div class="link-chips">${c.skills.map(s=>chip('skills',s)).join('')}</div></section></div><div class="note-box">Save review draft creates a local proposal and an exact before/after review. It does not apply settings to a runtime.</div><div class="row between">${act('Reset form to source','reset','config')}${act(icon('download')+' Export draft','export','config')}</div>`;},
 action(name){if(name==='reset'){S.drafts.config={};F.render();F.toast('Form restored to the source snapshot.');}if(name==='export')F.download('expert-config-demo.json',{demo:true,source:D.configs[0],draft:S.drafts.config||{}});if(name==='save'){const fields=Array.from(document.querySelectorAll('[data-config-field]'));if(fields.some(e=>!e.reportValidity()))return;const source=D.configs[0];const changed=Object.entries(S.drafts.config||{}).filter(([k,v])=>String(source.ui[k])!==String(v)).map(([field,after])=>({field,before:source.ui[field],after}));if(!changed.length){F.toast('No changes to review yet.');return;}const suffix=uid(),pid='prop_config_'+suffix,iid='intent_config_'+suffix;D.proposals.push({proposal_id:pid,tenant:'gbautomation',source_event_id:'evt_cap',producer_run_id:'producer_demo',source_type:'second_brain_item',workflow_route:'planning',state:'gated',task_id:null,card_title:'Review expert configuration',trace_id:'trace_demo_weekly',ui:{title:'Review expert configuration',icon:'settings',scope:'prd_demo_weekly',impact:changed.length+' settings',intent_id:iid,config_id:source.config_id,why:'A local draft is ready to compare.',diff:changed,before:changed[0].before,after:changed[0].after,field:changed[0].field}});D.intents.push({intent_id:iid,state:'PENDING_APPROVAL',subject_slug:'config-'+suffix,ui:{title:'Review configuration draft',icon:'settings',scope:'prd_demo_weekly',proposal_id:pid}});D.approvals.push({event_id:'event_'+uid(),intent_id:iid,event_type:'prepared',actor_kind:'automation',authorization_method:'none',ui:{title:'Draft prepared',icon:'clock',scope:'prd_demo_weekly',when:'Just now'}});F.navigate('changes',iid);F.toast('Demo proposal and review created from the exact draft.');}}
};
view.knowledge={
 preview(){const rows=F.scoped('sources'),r=F.chosen('knowledge');if(!r)return empty();return `<div class="row between"><span class="eyebrow">CONNECTED CONTEXT</span><span class="badge">${rows.length} sources</span></div><div class="network mini-network"><div class="network-node">${icon('message')}<strong>Sessions</strong></div><div class="network-node center">${icon('brain')}<strong>Second Brain</strong></div><div class="network-node">${icon('file')}<strong>Outputs</strong></div></div><div class="mini-list">${miniRow('sources',r,r.ui.tags.join(' · '))}</div>${miniAction('Explore context','knowledge','Sources → decisions → work')}`;},
 full(){const rows=F.filtered('knowledge',{type:r=>r.source_type,freshness:r=>r.ui.freshness}),r=F.selectedFrom('knowledge',rows);return filters('knowledge',[['type','Type',['file','transcript','memory','receipt']],['freshness','Freshness',['current','stale']]])+(r?`<div class="cards">${rows.map(s=>card('sources',s,meta(['file',s.source_type],['clock',s.ui.freshness]),'knowledge')).join('')}</div><div class="spaced">${hero(r,r.ui.summary,act(icon('message')+' Use as context','attach','knowledge','','primary'))}<div class="network"><div class="network-column">${F.neighbors('sources',r.source_artifact_id).filter(e=>e.kind==='sessions').slice(0,2).map(e=>`<div class="network-node">${icon('message')}<strong>Conversation</strong>${chip(e.kind,e.id)}</div>`).join('')||'<div class="network-node">'+icon('message')+'<strong>Context available</strong></div>'}</div><div class="network-node center">${icon(r.ui.icon)}<strong>${esc(r.title)}</strong>${badge(r.ui.freshness)}</div><div class="network-column">${F.neighbors('sources',r.source_artifact_id).filter(e=>e.kind==='artifacts'||e.kind==='proposals').slice(0,2).map(e=>`<div class="network-node">${icon(F.find(e.kind,e.id).ui.icon)}${chip(e.kind,e.id)}</div>`).join('')||'<div class="network-node">'+icon('file')+'<strong>No derived output yet</strong></div>'}</div></div><div class="subpanel">${line('Source type',r.source_type)}${line('Content available',r.content_mode)}${line('Redaction state',r.redaction_state)}${line('Source path',r.path)}</div></div>`:empty());},
 action(name){if(name==='attach'){const r=F.chosen('knowledge');if(!S.context.some(c=>c.kind==='sources'&&c.id===r.source_artifact_id))S.context.push({kind:'sources',id:r.source_artifact_id});F.navigate('chat');F.toast('Source attached as conversation context.');}}
};
view.tasks={
 preview(){const rows=F.scoped('tasks');return `<div class="row between"><span class="eyebrow">WORK IN MOTION</span><span class="badge">${rows.length} tasks</span></div><div class="mini-board spaced">${['ready','blocked','done'].map(status=>`<div class="mini-lane"><small>${F.human(status)}</small>${rows.filter(t=>t.status===status).slice(0,2).map(t=>`<button class="task-slip" data-open-kind="tasks" data-open-id="${t.task_id}">${icon(t.ui.icon)}${esc(t.title)}</button>`).join('')}</div>`).join('')}</div>${miniAction('Open workstream','tasks','Dependencies stay visible')}`;},
 full(){const rows=F.filtered('tasks',{status:r=>r.status,owner:r=>r.ui.owner==='Greg'?'Greg':'Expert'}),r=F.selectedFrom('tasks',rows);return filters('tasks',[['status','State',['ready','blocked','done']],['owner','Owner',['Greg','Expert']]])+tabbar('tasks',[['board','Board'],['dependencies','Dependencies']])+((S.tabs.tasks||'board')==='board'?`<div class="board">${['ready','blocked','done'].map(status=>`<section class="board-lane"><h4>${F.human(status)}<span>${rows.filter(t=>t.status===status).length}</span></h4>${rows.filter(t=>t.status===status).map(t=>`<button class="task-card ${r?.task_id===t.task_id?'selected':''}" data-select="${t.task_id}" data-select-window="tasks"><strong>${esc(t.title)}</strong><small>${icon('user')}${t.ui.owner==='Greg'?'Greg':'YouTube expert'} · ${t.ui.due}</small><div class="progress-track"><i style="width:${t.ui.progress}%"></i></div></button>`).join('')||'<p class="tiny muted">No tasks</p>'}</section>`).join('')}</div>`:`<div class="stack">${rows.map(t=>`<div class="dependency">${t.ui.depends_on.map(dep=>chip('tasks',dep)).join('')||'<span class="badge">No dependencies</span>'}${icon('arrow')}${chip('tasks',t.task_id)}${badge(t.status)}</div>`).join('')||empty()}</div>`)+(r?`<div class="subpanel spaced"><div class="row between wrap"><h4>${esc(r.title)}</h4>${r.status==='blocked'&&r.ui.intent_id?chip('intents',r.ui.intent_id,'Review blocker'):r.status!=='done'?act(icon('check')+' Complete demo task','complete','tasks','','primary'):badge('done')}</div>${line('Owner',r.ui.owner==='Greg'?'Greg':r.ui.owner)}<div class="link-chips">${r.ui.depends_on.map(x=>chip('tasks',x,'Dependency')).join('')}${D.artifacts.filter(a=>a.task_id===r.task_id&&a.is_latest).map(a=>chip('artifacts',a.artifact_id)).join('')}</div></div>`:empty());},
 action(name){if(name==='complete'){const t=F.chosen('tasks');if(t.ui.depends_on.some(id=>F.find('tasks',id).status!=='done')||(t.ui.intent_id&&F.find('intents',t.ui.intent_id).state!=='APPROVED')){F.toast('A dependency or approval is still pending.');return;}t.status='done';t.ui.progress=100;F.render();F.toast('Demo task completed across the workspace.');}}
};
view.artifacts={
 preview(){const rows=latestArtifacts();return `<div class="row between"><span class="eyebrow">THE OUTPUT LIBRARY</span><span class="badge">${rows.length} latest</span></div><div class="artifact-mini-grid spaced">${rows.slice(0,2).map(a=>`<button class="card" data-open-kind="artifacts" data-open-id="${a.artifact_id}">${thumb(a)}<strong>${esc(a.ui.title)}</strong><small>${a.version_label} · ${a.file_ext.toUpperCase()}</small></button>`).join('')}</div>${miniAction('Browse outputs','artifacts','Versioned and source-linked')}`;},
 full(){const rows=F.filtered('artifacts',{format:a=>a.file_ext,status:a=>a.approval,version:a=>a.is_latest?'Latest':'Previous'}),r=F.selectedFrom('artifacts',rows);return filters('artifacts',[['format','Format',['html','json']],['status','Review',['unreviewed','gb_approved','rejected']],['version','Version',['Latest','Previous']]])+`<div class="cards">${rows.map(a=>`<button class="card ${r?.artifact_id===a.artifact_id?'selected':''}" data-select="${a.artifact_id}" data-select-window="artifacts">${thumb(a)}<strong>${esc(a.ui.title)}</strong><small>${esc(a.ui.subtitle)}</small>${meta(['layers',a.version_label],['file',(a.bytes/1000).toFixed(1)+' KB'])}<div class="spaced">${badge(a.approval)}</div></button>`).join('')||empty()}</div>`+(r?`<div class="spaced">${hero(r,r.filename,chip('artifacts',r.artifact_id,'Open in canvas','canvas'))}${flow([['file','Source'],['terminal','Run'],['file',r.version_label],['eye',F.human(r.approval)]])}<div class="link-chips">${chip('sources',r.source_artifact_id)}${D.runArtifacts.filter(l=>l.artifact_id===r.artifact_id).map(l=>chip('runs',l.skill_run_id,'Producing run')).join('')}${chip('tasks',r.task_id,'Origin task')}</div>${line('Artifact family',r.artifact_family_id)}${line('Lifecycle',r.lifecycle)}${line('Stored copies',D.storage.filter(s=>s.artifact_id===r.artifact_id).length||'Receipt only')}</div>`:'');}
};
view.console={
 preview(){const r=F.chosen('console');if(!r)return empty();return `<div class="row between"><span class="eyebrow">LATEST EXECUTION</span>${badge(r.status)}</div><div class="run-duration-chart" aria-label="Sample run durations">${F.scoped('runs').slice(0,8).map(x=>`<button class="${x.status}" style="height:${Math.max(8,Math.min(42,x.elapsed_ms/300))}px" data-open-kind="runs" data-open-id="${x.run_id}" title="${esc(x.ui.title)} · ${(x.elapsed_ms/1000).toFixed(1)}s" aria-label="${esc(x.ui.title)}"></button>`).join('')}</div>${logs(r,true)}${miniAction('Open console','console',(r.elapsed_ms/1000).toFixed(1)+'s · Exit '+(r.ui.exit??'—'))}`;},
 full(){const rows=F.filtered('console',{status:r=>r.status,skill:r=>F.find('skills',r.skill_name)?.ui.category}),r=F.selectedFrom('console',rows);return filters('console',[['status','State',['ok','error','running','cancelled']],['skill','Category',['Research','Publishing','Quality','Context']]])+(r?`<div class="console-layout"><aside class="run-list">${rows.map(x=>`<button class="mini-row ${r.run_id===x.run_id?'selected':''}" data-select="${x.run_id}" data-select-window="console"><span class="${F.tone(x.status)}">${icon(x.status==='ok'?'check':x.status==='error'?'error':'clock')}</span><span><strong>${esc(x.ui.title)}</strong><small>${(x.elapsed_ms/1000).toFixed(1)}s · ${F.human(x.status)}</small></span></button>`).join('')}</aside><div>${hero(r,r.ui.command,S.job?act(icon('stop')+' Stop','stop','console','','danger'):act(icon('refresh')+' Run again','rerun','console','','primary'))}${metrics([[F.human(r.status),'State'],[(r.elapsed_ms/1000).toFixed(1)+'s','Duration'],[r.ui.exit??'—','Exit code']])}<div class="terminal-streams" role="group" aria-label="Terminal stream">${['all','stdout','stderr'].map(s=>`<button data-tab="${s}" data-tab-window="consoleStream" aria-pressed="${(S.tabs.consoleStream||'all')===s}">${s==='all'?'All output':s}</button>`).join('')}${act(icon('download'),'download','console','aria-label="Download sample run log"')}</div>${logs(r)}<div class="mini-action"><label class="field">Demo outcome<select data-setting="outcome"><option value="ok" ${S.outcome==='ok'?'selected':''}>Success</option><option value="error" ${S.outcome==='error'?'selected':''}>Error</option></select></label><span class="tiny muted">${runArtifacts(r).length} linked outputs</span></div><div class="link-chips">${runArtifacts(r).map(a=>chip('artifacts',a.artifact_id)).join('')}${r.parent_run_id?chip('runs',r.parent_run_id,'Parent run'):''}</div></div></div>`:empty());},
 action(name){const r=F.chosen('console');if(name==='rerun')F.run(r.skill_name,{title:r.ui.title,command:r.ui.command,scope:r.ui.scope});if(name==='download')F.download('demo-run-'+r.run_id+'.log',r.ui.lines.map(l=>'['+l[0]+'] '+l[1]).join('\n'));}
};
function proposalForIntent(i){return D.proposals.find(p=>p.ui.intent_id===i.intent_id);}
function diffs(p,mini=false){return (p.ui.diff||[{field:p.ui.field,before:p.ui.before,after:p.ui.after}]).slice(0,mini?1:99).map(d=>`<div><div class="section-label">${esc(d.field)}</div><div class="diff ${mini?'mini-diff':''}"><div class="diff-side"><small>BEFORE</small><strong>${esc(d.before)}</strong></div>${icon('arrow')}<div class="diff-side after"><small>AFTER</small><strong>${esc(d.after)}</strong></div></div></div>`).join('');}
view.changes={
 preview(){const i=F.chosen('changes');if(!i)return empty();const p=proposalForIntent(i);return `<div class="row between"><span class="eyebrow">${esc(i.ui.title)}</span>${badge(i.state)}</div>${p?diffs(p,true):empty('No proposal attached')}${miniAction('Review exact change','changes','Review is separate from execution')}`;},
 full(){const rows=F.filtered('changes',{status:i=>i.state}),i=F.selectedFrom('changes',rows);if(!i)return filters('changes',[['status','State',['PENDING_APPROVAL','APPROVED','REFUSED']]])+empty();const p=proposalForIntent(i);return filters('changes',[['status','State',['PENDING_APPROVAL','APPROVED','REFUSED']]])+select('changes',rows,'Change under review')+`<div class="spaced">${hero(i,p?.ui.why||'Inspect the proposed change.')}${badge(i.state)}${p?diffs(p):empty('No proposal attached')}<div class="row wrap"><span class="badge">${icon('box')}${esc(p?.ui.impact||'Scope pending')}</span><span class="badge">${icon('user')}Human review</span><span class="badge">${icon('lock')}Local simulation</span></div><div class="section-label">Review history</div>${D.approvals.filter(e=>e.intent_id===i.intent_id).map(e=>`<div class="event-line">${icon(e.event_type==='approved'?'check':e.event_type==='refused'?'error':'clock')}<span>${esc(e.ui.title)}</span><small>${esc(e.ui.when)}</small></div>`).join('')}<div class="decision-actions">${act(icon('check')+' Approve demo','approve','changes',i.state!=='PENDING_APPROVAL'?'disabled':'','primary')}${act('Decline demo','decline','changes',i.state!=='PENDING_APPROVAL'?'disabled':'')}</div><div class="note-box">This updates the local review fixture and its linked records. It does not authorize or execute a real change.</div><div class="link-chips">${p?chip('proposals',p.proposal_id,'Origin proposal'):''}${p?.ui.artifact_id?chip('artifacts',p.ui.artifact_id,'Exact artifact version','canvas'):''}${p?.ui.config_id?chip('configs',p.ui.config_id,'Source configuration'):''}</div></div>`;},
 action(name){if(!['approve','decline'].includes(name))return;const i=F.chosen('changes');if(i.state!=='PENDING_APPROVAL')return;const p=proposalForIntent(i),approved=name==='approve';i.state=approved?'APPROVED':'REFUSED';if(p){p.state=approved?'approved':'denied';if(p.ui.artifact_id)F.find('artifacts',p.ui.artifact_id).approval=approved?'gb_approved':'rejected';if(p.task_id&&approved){const t=F.find('tasks',p.task_id);if(t?.status==='blocked')t.status='ready';}}D.approvals.push({event_id:'event_'+uid(),intent_id:i.intent_id,event_type:approved?'modified':'shelved',actor_kind:'human',authorization_method:'none',ui:{title:approved?'Approved in design preview':'Declined in design preview',icon:approved?'check':'error',scope:i.ui.scope,when:'Just now',demo_only:true,demo_decision:approved?'approved':'declined'}});F.render();F.toast('Demo review updated. No real authorization was created.');}
};
})();
